protocol_1:
  text: "Welcome to the SoftEnable hospital robotic assistant demo!"
  image: unfolding_protocol/Image_01.png

protocol_bag_1:
  text: "While I open the bag, please, start by washing your hands."
  image: unfolding_protocol/Image_wash_hands.png
  frame: red
protocol_bag_2:
  text: "Please grasp the gloves from the bag and put them on"
  image: unfolding_protocol/gloves_compressed.png
  frame: green

protocol_bag_3:
  text: "Please remove the bag"
  frame: green

protocol_2:
  text: "While I prepare your gown, continue the dressing protocol standing in front of the counter"
  image: unfolding_protocol/Image_02.png
  frame: red

protocol_3:
  text: "Remove any jewelry or watch"
  image: unfolding_protocol/Image_03.png
  frame: red
protocol_4:
  text: "Tuck the inner coat into your trousers"
  image: unfolding_protocol/Image_04.png
  frame: red
protocol_5:
  text: "Tie up your hair and put on the cap"
  image: unfolding_protocol/Image_05.png
  frame: red
protocol_6:
  text: "Apply hand sanitizer"
  image: unfolding_protocol/Image_06.png
  frame: red
protocol_7:
  text: "Put on a second pair of gloves"
  image: unfolding_protocol/Image_07.png
  frame: red
  
protocol_8:
  text: "Take the gown I'm handing you and put it on"
  image: unfolding_protocol/Image_08.png
  frame: green

protocol_9:
  text: "Put on a face mask"
  image: unfolding_protocol/Image_09.png
protocol_10:
  text: "Put on the plastic apron"
  image: unfolding_protocol/Image_10.png
  
protocol_11:
  text: "Thank you! Now you can proceed to the surgery room."
  image: unfolding_protocol/Image_01.png