protocol_1:
  text: "Bienvenido a la demo del asistente robotico de SoftEnable!"
  image: unfolding_protocol/Image_01.png

protocol_bag_1:
  text: "Mientras abro la bolsa, por favor, pongase la mascarilla."
  image: unfolding_protocol/Image_09.png
  frame: red
protocol_bag_2:
  text: "Por favor, agarre los guantes de la bolsa y pongaselos."
  image: unfolding_protocol/gloves_compressed.png
  frame: green

protocol_bag_3:
  text: "Por favor, retira la bolsa."
  frame: green

protocol_2:
  text: "Mientras preparo la bata, continue con el protocolo"
  image: unfolding_protocol/Image_02.png
  frame: red

protocol_3:
  text: "Quitese cualquier joya o reloj"
  image: unfolding_protocol/Image_03.png
  frame: red
protocol_4:
  text: "Pongase la parte de arriba del pijama dentro de los pantalones"
  image: unfolding_protocol/Image_04.png
  frame: red
protocol_5:
  text: "Recojase el pelo y pongase el gorro"
  image: unfolding_protocol/Image_05.png
  frame: red
protocol_6:
  text: "Apliquese gel hidroalcoholico"
  image: unfolding_protocol/Image_06.png
  frame: red
protocol_7:
  text: "Pongase el primer par de guantes"
  image: unfolding_protocol/Image_07.png
  frame: red
  
protocol_8:
  text: "Recoja la bata que le estoy dando y pongasela"
  image: unfolding_protocol/Image_08.png
  frame: green

protocol_9:
  text: "Pongase la mascarilla"
  image: unfolding_protocol/Image_09.png
protocol_10:
  text: "Si es necesario, pongase el delantal"
  image: unfolding_protocol/Image_10.png
  
protocol_11:
  text: "Gracias! Ahora puede proceder a la sala."
  image: unfolding_protocol/Image_01.png